name: Welcome Greetings

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome New Contributors
        uses: actions/first-interaction@v3.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: |
            ## Hello there! 👋

            Thank you for opening your first issue! 🎉

            Before you continue, please take a moment to review our [Code of Conduct] and [Contribution Guidelines].
            These documents will help you understand our community and contribute effectively.

            We truly appreciate your effort!

            [Code of Conduct]: https://github.com/homelab-alpha/adguard-home/blob/main/CODE_OF_CONDUCT.md
            [Contribution Guidelines]: https://github.com/homelab-alpha/adguard-home/blob/main/CONTRIBUTING.md

          pr_message: |
            ## Hello there! 👋

            Thank you for submitting your first pull request! 🎉

            The Homelab-Alpha team will review your contribution as soon as possible.

            In the meantime, please make sure of the following:

            - ✅ Ensure all relevant documentation is updated.
            - ✅ Verify that all necessary tests are included and passing.
            - ✅ Check that CI/CD workflows complete successfully.

            We truly appreciate your effort and look forward to reviewing your pull request!
